=== mattisebastian/AutoKauf/AKWS1011GXX/WebContent/data/Autos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 <xsd:element name="AutoArrayItems" type="AutoArray"/>
 <xsd:complexType name="AutoArray">
 <xsd:sequence>
 <xsd:element name="AutoArrayItem" type="Auto" minOccurs="1" maxOccurs="unbounded"/>
 </xsd:sequence>
 </xsd:complexType>

<xsd:complexType name="Auto">
 <xsd:sequence>
 	<xsd:element name="autoID" type="xsd:long" />
 	<xsd:element name="farbe" type="xsd:string" />
 	<xsd:element name="anzahlSitze" type="xsd:int" />
 	<xsd:element name="gekauft" type="xsd:boolean" />
 	<xsd:element name="userID" type="xsd:long"/>
 </xsd:sequence>
</xsd:complexType>
</xsd:schema>

=== mattisebastian/AutoKauf/AKWS1011GXX/WebContent/data/Autos.xml
<?xml version="1.0" encoding="UTF-8"?>
<AutoArrayItems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Autos.xsd">
 <AutoArrayItem>
 <autoID>1</autoID>
 <farbe>rot</farbe>
 <anzahlSitze>4</anzahlSitze>
 <gekauft>false</gekauft>
 </AutoArrayItem>
 <AutoArrayItem>
 <autoID>2</autoID>
 <farbe>blau</farbe>
 <anzahlSitze>5</anzahlSitze>
 <gekauft>true</gekauft>
 </AutoArrayItem>
 <AutoArrayItem>
 <autoID>3</autoID>
 <farbe>dunkelorange</farbe>
 <anzahlSitze>8</anzahlSitze>
 <gekauft>true</gekauft>
 </AutoArrayItem>
 <AutoArrayItem>
 <autoID>4</autoID>
 <farbe>rosa</farbe>
 <anzahlSitze>3</anzahlSitze>
 <gekauft>true</gekauft>
 </AutoArrayItem>
 <AutoArrayItem>
 <autoID>5</autoID>
 <farbe>gruen</farbe>
 <anzahlSitze>5</anzahlSitze>
 <gekauft>true</gekauft>
 </AutoArrayItem>
 <AutoArrayItem>
 <autoID>6</autoID>
 <farbe>hellweiss</farbe>
 <anzahlSitze>2</anzahlSitze>
 <gekauft>true</gekauft>
 </AutoArrayItem>
</AutoArrayItems>
